### ISSUE TITLE
Bulk Processing of Files

### ISSUE THREAD

**Issue by Asbjoedt** [mikeebowen/OOXML-Validator#5] opened 2022-04-20 08:06 UTC
Hi.

We have the need to bulk process all files in a folder and with option to recursively also process any files in any subfolders. There should ideally be no limit to how many files can be processed during one command.

The output should be one XML file. 

Optionally, it could be an interesting feature to be able to specify which file formats should be looked for, in the folder. For instance 
`--xlsx --xlsm`
For any files created as Excel files and Excel files with macros.

**Comment by mikeebowen** [comment] 2022-04-20 15:32
I have not looked into validating all subfolders recursively, but I'll investigate and see if it's feasible. Adding flags for file types should be possible, I will have to think about how to implement it, it may need to go in a separate release. 

Regarding the XML returned. Do you need an XML file to be created or is a string of the XML sufficient? If you do need a file, would creating it in the root folder you pass to the CLI be sufficient or do you need to be able to specify where the file is saved?

**Comment by Asbjoedt** [comment] 2022-04-21 08:37
Great! I have seen adding `-r` as a parameter for recursively going down subfolders in this [software](https://github.com/RvanVeenendaal/Spreadsheet-Complexity-Analyser). How to program it, I don't know.

Having the XML in the command line is fine. I can append `> any_filename.xml` to output it as a file in XML. Maybe you can add this to documentation instead of programming.

Outputting the XML to file means it can be imported into Excel for data analysis of the bulk processed files.

**Comment by mikeebowen** [comment] 2022-04-21 18:49
Good call with adding `> any_filename.xml` that's simpler than adding it to the CLI itself. I looked at adding recursive analysis and it is possible and more straightforward than I thought it would be.

**Comment by mikeebowen** [comment] 2022-04-28 18:50
Hi @Asbjoedt ,

[Release 1.2.0](https://github.com/mikeebowen/OOXML-Validator/releases/tag/v1.2.0) adds the ability to validate single directories or recursively with a `-r` flag, so I will close this issue. Unfortunately, this does not fix the [incorrect validation issue](https://github.com/mikeebowen/OOXML-Validator/issues/6) caused by an error from the Open XML SDK, so I will keep that one open and work with the Open XML SDK team to fix the validation.

**Closed as completed by mikeebowen** 2022-04-28 18:50 UTC
Labels: enhancement
